Duplicate Entry bug Fix
Sprite3D caused Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: main.java.com.goxr3plus.xr3player.xplayer.visualizer.geometry.Sprite3D$Point3D.access$000(Lmain/java/com/goxr3plus/xr3player/xplayer/visualizer/geometry/Sprite3D$Point3D;)D
        at main.java.com.goxr3plus.xr3player.xplayer.visualizer.geometry.Sprite3D.transform(Sprite3D.java:431)
        at main.java.com.goxr3plus.xr3player.xplayer.visualizer.geometry.Sprite3D.draw(Sprite3D.java:361)

renamed it to Sprites3D and fuck yeah it works .. lol